name: BatdilFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.69.BETA
description: Plugin for the BatdilFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Bikkiester, Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
