name: BatdilFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the BatdilFreedom server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon, Bikkiester]

# plugin.yml is no longer used to define commands.
